# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  displayName: 'Build and Test'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet restore DotNetCoverletExample/DotNetCoverletExample.Counter/DotNetCoverletExample.Counter.csproj
    displayName: 'Restore'
    workingDirectory: $(System.DefaultWorkingDirectory)

  - script: dotnet build DotNetCoverletExample/DotNetCoverletExample.Counter/DotNetCoverletExample.Counter.csproj --configuration Release
    displayName: 'Build'
    workingDirectory: $(System.DefaultWorkingDirectory)

  - script: dotnet test DotNetCoverletExample/DotNetCoverletExample.Counter.Tests/DotNetCoverletExample.Counter.Tests.csproj --configuration Release --collect "Code coverage"
    displayName: 'Run Tests and Collect Code Coverage'
    workingDirectory: $(System.DefaultWorkingDirectory)


